- hosts: client
  remote_user: fedora
  become: yes
  gather_facts: no
  vars:
    WG_ADDR: 172.17.0.2/16
    LISTEN_PORT: 51820
    WG_ENDPOINT: 172.16.3.95:{{ LISTEN_PORT }}
    ALLOWED_IPS: 172.17.0.0/16,192.168.0.0/24
    WG_PUBKEY: +sQK+XXjdubXqm4rx3LFhP2CV3JlDgdTLo1nDN3iB3g=
  tasks:
    - name: install packages
      dnf:
        name:
          - wireguard-tools
          - iptables
    - name: generate private key
      shell: wg genkey | tee /etc/wireguard/wg_host_key
      register: private_key
    - name: generate public key
      shell: >
        cat /etc/wireguard/wg_host_key
        | wg pubkey
        | tee /etc/wireguard/wg_host_key.pub
      register: public_key
    - name: set facts
      set_fact:
        pubkey: '{{ public_key.stdout }}'
      delegate_to: '{{ item }}'
      delegate_facts: true
      with_items: "{{ groups['server'] }}"
    - name: set permission
      file:
        path: /etc/wireguard/{{ item }}
        mode: '0600'
      with_items:
        - wg_host_key
        - wg_host_key.pub
    - name: touch wireguard config file
      file:
        path: /etc/wireguard/wg0.conf
        state: touch
    - name: configure interface
      blockinfile:
        path: /etc/wireguard/wg0.conf
        block: |
          [Interface]
          PrivateKey = {{ private_key.stdout }}
          Address = {{ WG_ADDR }}
          [Peer]
          PublicKey = {{ WG_PUBKEY }}
          EndPoint = {{ WG_ENDPOINT }}
          AllowedIPs = {{ ALLOWED_IPS }}
    - name: enable service
      file:
        src: /usr/lib/systemd/system/wg-quick@.service
        path: /etc/systemd/system/multi-user.target.wants/wg-quick@wg0.service
        state: link
    - name: restart service
      systemd:
        name: wg-quick@wg0
        state: restarted
- hosts: server
  remote_user: fedora
  become: yes
  gather_facts: no
  vars:
    ALLOWED_IPS: 172.17.0.2/32
  tasks:
    - name: append peer
      shell: >
        echo -e "[Peer]\n
        PublicKey = {{ pubkey }}\n
        AllowedIPs = {{ ALLOWED_IPS }}\n"
        >> /etc/wireguard/wg0.conf
    - name: enable service
      file:
        src: /usr/lib/systemd/system/wg-quick@.service
        path: /etc/systemd/system/multi-user.target.wants/wg-quick@wg0.service
        state: link
    - name: restart service
      systemd:
        name: wg-quick@wg0
        state: restarted
